# Generated by Django 5.0.5 on 2024-05-07 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listpond", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlists",
            name="shared_with_users",
            field=models.ManyToManyField(
                blank=True, related_name="shared_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
